import type { Metadata } from "next";
import "./globals.css";
import { ReactReduxProvider } from "./react-redux-provider";
import { ReactQueryProvider } from "./react-query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ReactReduxProvider>{children}</ReactReduxProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
